import type { Workflow } from "@aart/types";
import { describe, expect, it } from "vitest";
import { renderApprovalSummary } from "./approval-summary.js";
import type { CapabilityClosureResult } from "./capability.js";

// A "kitchen sink" fixture populating EVERY Workflow and WorkflowStep field
// — this is what proves the renderer's covered-field registry isn't just
// declared but actually exercised. trust-surface-completeness.test.ts
// checks the registry against the schema; this file checks the registry
// against the renderer's actual OUTPUT.
const kitchenSinkWorkflow: Workflow = {
  id: "checkout-smoke",
  name: "Checkout Smoke Test",
  version: "0.2.0",
  inputs: [{ name: "url", type: "string", required: true, description: "target URL", default: "https://example.com", enum: undefined, pattern: undefined }],
  outputs: [{ name: "screenshotPath", type: "string" }],
  execution: {
    type: "workflow",
    steps: [
      {
        id: "open",
        uses: "browser.goto",
        with: { url: "{{ inputs.url }}" },
        if: "{{ inputs.url }}",
        then: "read",
        else: "fail",
        next: "read",
        forEach: "{{ inputs.items }}",
        as: "item",
        maxIterations: 6,
        until: "{{ steps.open.outputs.done }}",
        retry: { maxAttempts: 3, backoff: "exponential", retryOn: ["timeout"] },
        timeout: "30s",
        idempotencyKey: "{{ run.id }}:open",
      },
      { id: "read", uses: "web.read" },
      { id: "fail", uses: "flow.fail" },
    ],
    outputMapping: { screenshotPath: "{{ steps.screenshot.outputs.path }}" },
  },
  approval: "approved",
  gates: { validate: "passed", readiness: "passed", evals: "passed", riskReview: "passed", humanReview: "passed" },
  category: "smoke-test",
  keywords: ["checkout", "browser"],
  examples: [{ description: "basic run", inputs: { url: "https://example.com" } }],
  generatedByModel: "anthropic/claude-sonnet-5",
  needsReview: true,
  promotionBlocked: true,
};

const closure: CapabilityClosureResult = {
  capabilities: ["browser", "secrets:GITHUB_TOKEN", "domain:api.github.com"],
  riskTier: "High",
  unresolved: [],
};

describe("renderApprovalSummary (spec §17.3)", () => {
  const rendered = renderApprovalSummary({
    workflow: kitchenSinkWorkflow,
    capabilityClosure: closure,
    writes: ["screenshot artifact only"],
    riskNotes: ["Uses secret GITHUB_TOKEN"],
    effectfulWithoutIdempotencyKey: ["fail"],
  });

  it("renders the header as Workflow: <id>@<version>, matching the spec's own example format", () => {
    expect(rendered).toContain("Workflow: checkout-smoke@0.2.0");
  });

  it("renders every WorkflowStep field present in the kitchen-sink fixture", () => {
    expect(rendered).toContain("[open]"); // id
    expect(rendered).toContain("Run browser.goto"); // uses
    expect(rendered).toContain('"url":"{{ inputs.url }}"'); // with (JSON-embedded)
    expect(rendered).toContain("if {{ inputs.url }}"); // if
    expect(rendered).toContain("then -> read"); // then
    expect(rendered).toContain("else -> fail"); // else
    expect(rendered).toContain("next -> read"); // next
    expect(rendered).toContain("for each item in {{ inputs.items }}"); // forEach + as
    expect(rendered).toContain("max 6 iterations"); // maxIterations
    expect(rendered).toContain("until {{ steps.open.outputs.done }}"); // until
    expect(rendered).toContain("retry up to 3x (exponential)"); // retry
    expect(rendered).toContain("timeout 30s"); // timeout
    expect(rendered).toContain("idempotencyKey {{ run.id }}:open"); // idempotencyKey
  });

  it("renders every Workflow-level field present in the kitchen-sink fixture", () => {
    expect(rendered).toContain("(Checkout Smoke Test)"); // name
    expect(rendered).toContain("- url: string"); // inputs
    expect(rendered).toContain("- screenshotPath: string"); // outputs
    expect(rendered).toContain("Approval: approved"); // approval
    expect(rendered).toContain("- validate: passed"); // gates
    expect(rendered).toContain("Category: smoke-test"); // category
    expect(rendered).toContain("Keywords: checkout, browser"); // keywords
    expect(rendered).toContain("Examples: 1 provided"); // examples
    expect(rendered).toContain("Generated by: anthropic/claude-sonnet-5"); // generatedByModel
    expect(rendered).toContain("Needs review"); // needsReview
    expect(rendered).toContain("Promotion blocked"); // promotionBlocked
  });

  it("renders capabilities/secrets/external-systems/writes/risk sections from the capability closure", () => {
    expect(rendered).toContain("Capabilities:");
    expect(rendered).toContain("- browser");
    expect(rendered).toContain("Secrets:");
    expect(rendered).toContain("- GITHUB_TOKEN");
    expect(rendered).toContain("External systems:");
    expect(rendered).toContain("- api.github.com");
    expect(rendered).toContain("Writes:");
    expect(rendered).toContain("- screenshot artifact only");
    expect(rendered).toContain("Risk: High");
    expect(rendered).toContain("Risk notes:");
    expect(rendered).toContain("- Uses secret GITHUB_TOKEN");
  });

  it("renders the effectful-without-idempotencyKey WARNING without blocking (it's advisory text, not an exception)", () => {
    expect(rendered).toContain("Warnings:");
    expect(rendered).toContain('step "fail" declares an effectful capability with no idempotencyKey');
  });

  it("matches the spec's low-risk example structure for a minimal workflow (Capabilities/External systems/Secrets/Writes/Risk, in order)", () => {
    const minimal: Workflow = {
      id: "checkout-smoke",
      name: "n",
      version: "0.1.0",
      inputs: [],
      outputs: [],
      execution: { type: "workflow", steps: [] },
      approval: "draft",
      gates: { validate: "pending", readiness: "pending", evals: "pending", riskReview: "pending", humanReview: "pending" },
    };
    const minimalClosure: CapabilityClosureResult = { capabilities: ["browser"], riskTier: "Low", unresolved: [] };
    const output = renderApprovalSummary({ workflow: minimal, capabilityClosure: minimalClosure });
    const capIdx = output.indexOf("Capabilities:");
    const secretsIdx = output.indexOf("Secrets:");
    const externalIdx = output.indexOf("External systems:");
    const writesIdx = output.indexOf("Writes:");
    const riskIdx = output.indexOf("Risk:");
    expect(capIdx).toBeGreaterThanOrEqual(0);
    expect(externalIdx).toBeGreaterThan(capIdx);
    expect(secretsIdx).toBeGreaterThan(externalIdx);
    expect(writesIdx).toBeGreaterThan(secretsIdx);
    expect(riskIdx).toBeGreaterThan(writesIdx);
    expect(output).toContain("Secrets:\n- none");
    expect(output).toContain("Writes:\n- none");
  });
});
