// Reviewed suppressions for the redaction-bypass lint (root AMENDMENTS.md,
// S10 completion — "the lint supports exclusions — extend its config, don't
// weaken its detection"). Each entry is a DELIBERATE, individually-reviewed
// decision that one specific call site's `RedactionLintFinding` is a false
// positive — never a way to make the lint quieter in general. The
// detection logic in `redaction-lint.ts` is completely unchanged by this
// file; every suppressed finding is still COMPUTED, just filtered out of
// the CI-facing failure count by `redaction-lint-cli.ts`, and the CLI
// still reports how many were suppressed (not silently dropped from view).
//
// Matched on (file relative to repo root, exact trimmed source line) rather
// than (file, line number): a line-number key would silently keep
// "suppressing" whatever ends up on that line after an unrelated edit
// shifts things around — the file+snippet pair breaks (forcing a fresh,
// deliberate look) the moment the guarded code actually changes, which is
// the correct failure mode for a REVIEWED suppression list.
//
// A41 (root AMENDMENTS.md, S10 Completion): populated by triaging all 186
// findings from the first real repo-wide run. One genuine bypass was found
// and fixed as CODE, not suppressed here — see packages/engine/src/
// step-executor.ts's executeWaitDispatch (human.approval ApprovalTask
// creation now routes through applyRedaction). Every entry below was
// individually verified by reading the guarded call site's actual
// surrounding code (and, where relevant, the call chain it feeds into) —
// see A41 for the full taxonomy and reasoning.
export interface RedactionLintSuppression {
  readonly file: string; // relative to repo root, e.g. "packages/mcp/src/stubs/foo.ts"
  readonly snippet: string; // the finding's exact trimmed source line — see RedactionLintFinding.snippet
  readonly reason: string; // one line: why this specific call site is NOT a real bypass
}

export const REDACTION_LINT_SUPPRESSIONS: readonly RedactionLintSuppression[] = [

  // ---- packages/cli/src/commands/deployment.ts ----
  { file: "packages/cli/src/commands/deployment.ts", snippet: "await cli.aart.store.deployments.put(updated);", reason: "triggerAddCommand writes Deployment.triggerConfig from CLI flags (mode/webhook-path/webhook-hmac-secret-ref/cron/...) -- webhook-hmac-secret-ref is a symbolic REF/name (S2 SEAMS.md TriggerBinding shape), never a resolved secret value; same class as deployment/trigger configuration elsewhere, outside resolvedSecretRefs' scope." },

  // ---- packages/cli/src/stubs/server.ts ----
  { file: "packages/cli/src/stubs/server.ts", snippet: "await store.runs.put(updated);", reason: "clearRunFlag spreads an existing RunRecord (already redacted at creation by whichever engine wrote it) with only a static { clearedBy, clearedAt } flag object added -- no new arbitrary content enters the record." },

  // ---- packages/dashboard/src/stub-deps.ts ----
  { file: "packages/dashboard/src/stub-deps.ts", snippet: "await store.runs.put(updated);", reason: "Shared source line, 3 call sites: makeClearRunFlag (spreads an existing RunRecord + a static clearedBy/clearedAt flag object) and updateRunOutput's two branches (writes correction.corrected into outputs/trace -- human/agent-authored correction data entered via a later, separate MCP/CLI call, never a live run's resolvedSecretRefs-tracked value; see evidence/corrections/outcomes.ts for the identical, canonical implementation of this same operation)." },
  { file: "packages/dashboard/src/stub-deps.ts", snippet: "await store.runs.put(run);", reason: "makeTriggerRunAndEnqueue persists a fresh \"pending\" RunRecord shell before any step has executed -- inputs/trigger are copied verbatim from the caller, never resolved (no @aart/expr/secrets pipeline runs here); real step execution + redaction happens later when a worker executes this run through the real @aart/engine (verified: every engine mutation is redacted before persist/return, run-lifecycle.ts/step-executor.ts/wait-machine.ts)." },
  { file: "packages/dashboard/src/stub-deps.ts", snippet: "await tx.runs.put(updated);", reason: "makeResumeApproval spreads an existing RunRecord with only status/updatedAt/a filtered waits array -- no new arbitrary content, matching @aart/engine's own resumeApproval mechanism's shape." },
  { file: "packages/dashboard/src/stub-deps.ts", snippet: "await store.approvals.put(updated);", reason: "makeDecideApprovalTask's `decision` parameter is human/agent-authored free-form decision rationale supplied directly to this call, not data flowing through a live run's secret-resolution pipeline -- same class as Correction.observed/corrected (evidence/corrections/correction.ts)." },
  { file: "packages/dashboard/src/stub-deps.ts", snippet: "await store.corrections.put(correction);", reason: "makeRecordCorrection -- Correction.observed/corrected are human/agent-authored free-form correction data entered via a separate MCP/CLI call, disconnected from any live run's resolvedSecretRefs (that set is scoped to one triggerRun/executeRun call and is never persisted for reuse); see evidence/corrections/correction.ts for the full reasoning, identical here." },

  // ---- packages/engine/src/concurrency.ts ----
  { file: "packages/engine/src/concurrency.ts", snippet: "await store.runs.put(released);", reason: "releaseQueuedRuns only flips params.waitingOnConcurrency to false on an existing \"pending\" RunRecord -- every pending RunRecord in the store was already redacted at creation by triggerRun (run-lifecycle.ts:94, applyRedaction before the first store.runs.put) and is never mutated between creation and this release, so this write introduces no new, never-redacted content." },

  // ---- packages/engine/src/wait/wait-machine.ts ----
  { file: "packages/engine/src/wait/wait-machine.ts", snippet: "await tx.approvals.put({ ...task, status: \"expired\", decidedAt: now.toISOString() });", reason: "failExpiredWait spreads an existing ApprovalTask (redacted at creation by step-executor.ts's executeWaitDispatch, A41 fix) with only a static status/decidedAt pair added -- introduces no new content." },

  // ---- packages/evidence/src/corrections/correction.ts ----
  { file: "packages/evidence/src/corrections/correction.ts", snippet: "await store.corrections.put(parsed);", reason: "Correction.observed/corrected are human/agent-authored free-form correction data, entered via aart_record_correction / aart correction add -- a separate, later MCP/CLI call structurally disconnected from any live run's execution. No resolvedSecretRefs set is obtainable here: that set (@aart/engine/src/redaction.ts) is scoped to a single triggerRun/executeRun call and is never persisted for later reuse. Under normal use there is nothing unredacted to reintroduce either: the RunRecord a correction is ABOUT was already fully redacted (verified end-to-end) by the time any human/agent could read it to formulate the correction. Residual, disclosed limitation: an agent could in principle type a secret it learned out-of-band directly into observed/corrected -- structurally the same as any other free-text field, outside what value-scan-and-replace against a known resolved-secret set can ever catch." },

  // ---- packages/evidence/src/corrections/outcomes.ts ----
  { file: "packages/evidence/src/corrections/outcomes.ts", snippet: "await store.runs.put(updatedRun);", reason: "updateRunOutput patches an existing (already-redacted) RunRecord's outputs/trace with correction.corrected -- same reasoning as correction.ts: human/agent-authored correction data with no resolvedSecretRefs pipeline reaching this call site." },

  // ---- packages/familiarity-evals/src/ci-gate.ts ----
  { file: "packages/familiarity-evals/src/ci-gate.ts", snippet: "console.error(`familiarity-evals ci-gate: no scripted response for task(s): ${missing.map((t) => t.id).join(\", \")}`);", reason: "Prints static AUTHORING_TASK_CATALOG task ids (hardcoded catalog, catalog.ts) missing a SCRIPT entry -- a harness config error message, not run/secret data." },
  { file: "packages/familiarity-evals/src/ci-gate.ts", snippet: "console.log(\"familiarity-evals CI gate (fake model — see this file's own doc comment for why no real model is used here):\\n\");", reason: "Static hardcoded banner string literal -- no variable data at all." },
  { file: "packages/familiarity-evals/src/ci-gate.ts", snippet: "console.log(`  [${status}] ${r.taskId}  firstDraftValid=${r.firstDraftValid} correctBlockChoice=${r.correctBlockChoice} ranSuccessfully=${r.ranSuccessfully} score=${r.score.toFixed(2)}`);", reason: "Prints per-task scoring metrics (task id from the static catalog, booleans, a numeric score) computed from the SCRIPT's hardcoded fake-model responses -- no secret-shaped data anywhere in this fake-model-only harness." },
  { file: "packages/familiarity-evals/src/ci-gate.ts", snippet: "console.log(`\\nMetrics: firstDraftValidityRate=${metrics.firstDraftValidityRate.toFixed(2)} averageLoopsToValid=${metrics.averageLoopsToValid} correctBlockChoiceRate=${metrics.correctBlockChoiceRate.toFixed(2)}`);", reason: "Prints aggregate numeric metrics derived from the fake-model run -- no secret-shaped data." },
  { file: "packages/familiarity-evals/src/ci-gate.ts", snippet: "console.error(`\\nfamiliarity-evals ci-gate: ${failed.length}/${results.length} task(s) failed.`);", reason: "Prints a pass/fail count summary -- two integers, no run content." },
  { file: "packages/familiarity-evals/src/ci-gate.ts", snippet: "console.log(`\\nfamiliarity-evals ci-gate: all ${results.length} tasks passed (fake-model harness verification — not a real-model baseline, see module doc comment).`);", reason: "Prints a static success banner plus a task count -- no run content." },
  { file: "packages/familiarity-evals/src/ci-gate.ts", snippet: "console.error(err);", reason: "main().catch's top-level error logger -- this entire script runs only against createFakeModelRunner's hardcoded SCRIPT (module doc comment: \"No LLM provider API key is available in the environment this was built in\"), so any thrown error here is a harness code/logic error, never a value that could carry a resolved secret." },

  // ---- packages/llm/src/registry.ts ----
  { file: "packages/llm/src/registry.ts", snippet: "await store.promptRegistry.put(entry);", reason: "registerPrompt persists author-registered, versioned, content-hashed prompt TEXT at authoring/registration time -- configuration content analogous to a workflow definition, not a live run's resolved secret value." },
  { file: "packages/llm/src/registry.ts", snippet: "await store.schemaRegistry.put(entry);", reason: "registerSchema persists an author-registered, versioned, content-hashed JSON Schema body at authoring/registration time -- same reasoning as registerPrompt above." },

  // ---- packages/mcp/src/catalog.ts ----
  { file: "packages/mcp/src/catalog.ts", snippet: "return m;", reason: "The `manifest(m)` identity helper returns its own input unchanged -- m is a hardcoded BlockManifest literal from this file's static BLOCKS array (compile-time-authored tool/block descriptions), never runtime data." },

  // ---- packages/mcp/src/context.ts ----
  { file: "packages/mcp/src/context.ts", snippet: "return \"governed\";", reason: "resolveTrustModeFromEnv's fallback branch returns a fixed TrustMode string literal -- not a data-emission path." },
  { file: "packages/mcp/src/context.ts", snippet: "return { store, engine, governance, evidence, registry, trustMode, now };", reason: "createAartContext returns the AartContext container itself (store handle, port objects made of methods, a trustMode enum string, a clock function) -- a dependency-injection bundle, not a persisted/emitted data record." },
  { file: "packages/mcp/src/context.ts", snippet: "return { context: { store, engine, governance, evidence, registry, trustMode, now }, engine: realEngine };", reason: "A42: createRealAartContextWithEngine's return -- same AartContext DI-bundle as the createAartContext entry above (store handle, port objects, trustMode string, clock function), plus the raw Engine instance (itself an object of methods, not data) so @aart/cli's real ServerPort can share it. Nothing here is persisted/emitted run or record data." },
  { file: "packages/mcp/src/context.ts", snippet: "return createRealAartContextWithEngine(options).context;", reason: "A42: createRealAartContext's body after being refactored to delegate to createRealAartContextWithEngine (same function, same reasoning as that function's own entry above) -- unwraps the DI bundle from a container that is itself covered by the entry directly above." },

  // ---- packages/mcp/src/handlers/authoring.ts ----
  { file: "packages/mcp/src/handlers/authoring.ts", snippet: "return {", reason: "validateWorkflowHandler's compile-failure branch returns { ok, valid, error: err.message, findings } -- a YamlCompileError's own message plus schema-validation findings describing what is structurally wrong with the DRAFT the caller just supplied (their own input echoed back for correction), never a resolved run secret." },
  { file: "packages/mcp/src/handlers/authoring.ts", snippet: "return { ok: false, error: \"Provide either `workflow` (a draft) or `workflowId`+`workflowVersion` (a registered version).\" };", reason: "Static, hardcoded error string literal -- no variable data." },
  { file: "packages/mcp/src/handlers/authoring.ts", snippet: "return { ok: result.valid, valid: result.valid, findings: result.findings };", reason: "Returns ctx.governance.validateWorkflow's findings -- schema/reference/capability validation diagnostics about the workflow DEFINITION's structure (unresolved, pre-execution), never a resolved run secret." },
  { file: "packages/mcp/src/handlers/authoring.ts", snippet: "return { ok: true, workflowId: draft.id, workflowVersion: draft.version, approval: draft.approval };", reason: "Returns only id/version/approval-state metadata of the just-registered draft workflow -- not the workflow body, and none of it is run-resolved data." },

  // ---- packages/mcp/src/handlers/deployment.ts ----
  { file: "packages/mcp/src/handlers/deployment.ts", snippet: "await ctx.store.environments.put(env);", reason: "ensureEnvironment auto-vivifies a minimal Environment ({ id, name, config: {} }) on first deploy -- config is a hardcoded empty object; name is the caller-supplied deploy target string. No resolved secret data." },
  { file: "packages/mcp/src/handlers/deployment.ts", snippet: "return env;", reason: "Returns the just-created/looked-up Environment record (id/name/empty config) -- deployment target metadata, not run data." },
  { file: "packages/mcp/src/handlers/deployment.ts", snippet: "return { ok: false, error: `Deployment refused: ${evaluation.reason} for ${input.workflowId}@${input.workflowVersion}.`, reason: evaluation.reason };", reason: "evaluation.reason is one of governance's fixed promotion-refusal reason codes (e.g. \"promotion_blocked\") -- a static vocabulary token, and workflowId/workflowVersion are caller-supplied identifiers, never resolved run secrets." },
  { file: "packages/mcp/src/handlers/deployment.ts", snippet: "return {", reason: "deployWorkflowHandler's unmet-gates branch returns { ok: false, error, unmetGates: evaluation.record.unmetGates } -- unmetGates is an array of governance gate-name enum values (e.g. \"validate\"/\"humanReview\"), not run data." },
  { file: "packages/mcp/src/handlers/deployment.ts", snippet: "await ctx.store.deployments.put(deployment);", reason: "The Deployment record is built entirely from workflowId/workflowVersion/environment.id (caller/lookup-supplied identifiers) plus an empty triggerConfig object and a timestamp -- no run-resolved data." },
  { file: "packages/mcp/src/handlers/deployment.ts", snippet: "return { ok: true, deployment, environment };", reason: "Returns the just-created Deployment/Environment metadata records described above -- identifiers and config, no run-resolved secret content." },
  { file: "packages/mcp/src/handlers/deployment.ts", snippet: "return { ok: outcome.kind === \"resumed\", kind: \"signal\", outcome };", reason: "outcome is @aart/engine's ResumeOutcome, whose embedded RunRecord (outcome.run) is always the already-redacted record returned by wait-machine.ts's claimAndCompleteWait (verified: applyRedaction runs immediately before every \"return { kind: 'resumed', run: redacted, ... }\")." },
  { file: "packages/mcp/src/handlers/deployment.ts", snippet: "return { ok: false, error: `Workflow \"${input.workflowId}\" is not deployed anywhere. Call aart_deploy_workflow first.` };", reason: "input.workflowId is a caller-supplied identifier interpolated into a static error string -- not resolved run data." },
  { file: "packages/mcp/src/handlers/deployment.ts", snippet: "return { ...runResult, kind: \"run\" };", reason: "runResult is runWorkflowHandler's own return value (handlers/execution.ts) -- see that handler's own entries below: it surfaces finished.outputs/trace, both sourced from @aart/engine's executeRun, whose returned RunRecord is always already-redacted (verified end-to-end across run-lifecycle.ts/step-executor.ts/wait-machine.ts)." },
  { file: "packages/mcp/src/handlers/deployment.ts", snippet: "return { ok: outcome.kind === \"resumed\", outcome };", reason: "Same ResumeOutcome reasoning as the \"signal\" branch above -- outcome.run is always the already-redacted record wait-machine.ts's claimAndCompleteWait/enterWait return." },

  // ---- packages/mcp/src/handlers/discovery.ts ----
  { file: "packages/mcp/src/handlers/discovery.ts", snippet: "return {", reason: "findBlocksHandler returns { ok, query: input.query, blocks: results.map(...) } -- block search results drawn from the static, compile-time BUILTIN_BLOCK_CATALOG (catalog.ts) filtered/scored against the caller's own query text; no run-resolved secret data anywhere in a block manifest." },
  { file: "packages/mcp/src/handlers/discovery.ts", snippet: "return { ok: true, block: entry.manifest, packName: entry.packName, examples: entry.examples };", reason: "entry.manifest is a static BlockManifest from the compile-time catalog (id/description/capabilities/schemas) -- never touches a live run's resolved secrets." },
  { file: "packages/mcp/src/handlers/discovery.ts", snippet: "return { ok: true, blocks: filtered.map((e) => e.manifest), count: filtered.length };", reason: "Same static catalog data as above (listBlocksHandler)." },
  { file: "packages/mcp/src/handlers/discovery.ts", snippet: "return { ok: true, kind: \"workflow\", schema: toJsonSchema(WorkflowSchema) };", reason: "toJsonSchema(WorkflowSchema) derives a JSON Schema from the frozen, hardcoded @aart/types Zod schema -- pure static type metadata." },
  { file: "packages/mcp/src/handlers/discovery.ts", snippet: "return { ok: true, kind: \"block\", blockId: input.blockId, inputSchema: entry.manifest.inputSchema, outputSchema: entry.manifest.outputSchema };", reason: "entry.manifest.inputSchema/outputSchema are static, compile-time-authored JSON Schemas from the block catalog -- not run data." },

  // ---- packages/mcp/src/handlers/evals.ts ----
  { file: "packages/mcp/src/handlers/evals.ts", snippet: "return { ok: false, error: `No correction found for run \"${input.runId}\" step \"${input.stepId}\"${input.fieldPath ? ` field \"${input.fieldPath}\"` : \"\"}. Call aart_record_correction first.` };", reason: "Interpolates only caller-supplied identifiers (runId/stepId/fieldPath) into a static error string -- not resolved run data." },
  { file: "packages/mcp/src/handlers/evals.ts", snippet: "return { ok: true, example };", reason: "example is ctx.evidence.createEvalExampleFromCorrection's return value -- built from Correction fields (observed/corrected), the same human/agent-authored correction data class covered by evidence/corrections/correction.ts's suppression above, not run-resolved secret data." },
  { file: "packages/mcp/src/handlers/evals.ts", snippet: "return { ok: evalRun.failed === 0, evalRun };", reason: "evalRun is aggregate pass/fail/score summary data (EvalRun: total/passed/failed/score/regressions[]/improvements[] of example ids) -- verified via evidence/src/evals/run-suite.ts's runEvalSuite: it carries no raw example content, only ids and counts." },

  // ---- packages/mcp/src/handlers/execution.ts ----
  { file: "packages/mcp/src/handlers/execution.ts", snippet: "return workflowVersion ? ctx.store.workflows.get(workflowId, workflowVersion) : ctx.store.workflows.getLatest(workflowId);", reason: "resolveWorkflow returns a Workflow DEFINITION (unresolved -- template strings like \"{{ secrets.X }}\" are never evaluated by a store read) -- the pre-execution/authoring stage of the pipeline, not a post-secret-resolution value. This return value is internal (feeds runWorkflowHandler), never itself an MCP tool's client-facing result." },
  { file: "packages/mcp/src/handlers/execution.ts", snippet: "return run.trace.map((t) => ({ stepId: t.stepId, block: t.block, status: t.status, error: t.error }));", reason: "summarizeTrace reads from an already-redacted RunRecord (t comes from run.trace, and every RunRecord returned by @aart/engine is redacted before return, verified end-to-end) -- error is the failure message already inside that redacted trace entry." },
  { file: "packages/mcp/src/handlers/execution.ts", snippet: "return {", reason: "runWorkflowHandler's success return: { ok, runId, status, outputs: finished.outputs, error: finished.error, trace: summarizeTrace(finished) } -- finished is ctx.engine.executeRun()'s return value, always the already-redacted RunRecord (run-lifecycle.ts's executeRun -> runStepsLoop -> finalizeTerminal, which returns `redacted` immediately after applyRedaction; verified this holds for every exit path, including the pre-existing-terminal-status early return, since a stored RunRecord was itself redacted when first persisted)." },
  { file: "packages/mcp/src/handlers/execution.ts", snippet: "return result;", reason: "getReportHandler returns { ok: true, report, markdown? } -- report/markdown come from ctx.evidence.modelFacingReport/markdownReport(run), and `run` is read from ctx.store.runs.get(), i.e. an already-persisted (already-redacted, per @aart/engine's invariant) RunRecord." },
  { file: "packages/mcp/src/handlers/execution.ts", snippet: "return compiled;", reason: "ensureVerifyWorkflow returns a freshly-compiled synthetic Workflow DEFINITION (hardcoded steps: browser.goto/web.read/assert.contains/browser.screenshot) -- pre-execution, unresolved-template stage, never touches a resolved secret." },
  { file: "packages/mcp/src/handlers/execution.ts", snippet: "return { ok: report.headline === \"passed\", report, runId: run.runId };", reason: "verifyHandler -- same modelFacingReport(run) reasoning as getReportHandler above: run is read back from the store, already redacted." },

  // ---- packages/mcp/src/handlers/governance.ts ----
  { file: "packages/mcp/src/handlers/governance.ts", snippet: "return { ok: false, error: \"Provide either (workflowId + workflowVersion) or (runId + stepId).\" };", reason: "Static, hardcoded error string literal -- no variable data." },
  { file: "packages/mcp/src/handlers/governance.ts", snippet: "return { ok: true, taskId: task.id, runId: task.runId, stepId: task.stepId };", reason: "task comes from ctx.governance.writeApprovalDecision, which routes through this package's redact() (stubs/governance.ts) before persisting -- and only id/runId/stepId identifiers are returned here, not title/description/decision content." },
  { file: "packages/mcp/src/handlers/governance.ts", snippet: "return { ok: true, kind: \"workflow_version\", workflowId, workflowVersion, gates, approval };", reason: "gates/approval are governance state-machine enum values (e.g. \"passed\"/\"waived\"/\"approved\") computed by computeApprovalState -- fixed vocabulary, not resolved secret data." },
  { file: "packages/mcp/src/handlers/governance.ts", snippet: "return applyVersionReviewDecision(ctx, versionReview.workflowId, versionReview.workflowVersion, input.decision);", reason: "Delegates to applyVersionReviewDecision, covered by the \"workflow_version\" entry directly above (identical return shape)." },
  { file: "packages/mcp/src/handlers/governance.ts", snippet: "return { ok: outcome.kind === \"resumed\", kind: \"run_step\", runId: task.runId, stepId: task.stepId, outcome };", reason: "Same ResumeOutcome reasoning established for handlers/deployment.ts: outcome.run is always the already-redacted RunRecord wait-machine.ts's claimAndCompleteWait returns." },
  { file: "packages/mcp/src/handlers/governance.ts", snippet: "return { ok: true, correction };", reason: "correction is ctx.evidence.recordCorrection's return value -- Correction is human/agent-authored data supplied directly as this same call's own input (recordCorrectionHandler's `input`), simply echoed back with a createdAt stamp; see evidence/corrections/correction.ts's suppression for the full reasoning on why Correction content is outside resolvedSecretRefs' scope." },
  { file: "packages/mcp/src/handlers/governance.ts", snippet: "return { ok: true, workflowId: input.workflowId, fromVersion: input.fromVersion, toVersion: input.toVersion, diff };", reason: "diff is governance's semanticRiskDiff output -- step-level added/removed/modified summaries (block ids + static change-description strings like \"step parameters changed\", never the actual with: values) plus capability-risk booleans." },
  { file: "packages/mcp/src/handlers/governance.ts", snippet: "return { ok: approval === \"approved\", workflowId: input.workflowId, workflowVersion: input.workflowVersion, approval, requiredGates, unmetGates };", reason: "approval/requiredGates/unmetGates are governance gate-name/state enum values -- fixed vocabulary, not resolved secret data." },

  // ---- packages/mcp/src/init-agent.ts ----
  { file: "packages/mcp/src/init-agent.ts", snippet: "return { mcpConfig, mcpConfigJson, instructions };", reason: "Returns static, hardcoded MCP client config (npx invocation shape) and a hardcoded markdown instructions document, parameterized only by options.packageName (a package identifier string) and options.trustMode (one of 4 fixed enum values) -- no secret-shaped data anywhere." },

  // ---- packages/mcp/src/mcp-stdio.ts ----
  { file: "packages/mcp/src/mcp-stdio.ts", snippet: "return {", reason: "startMcpStdioServer returns { mcpServer, transport, close } -- SDK server/transport object handles and a close() function, never application record data." },

  // ---- packages/mcp/src/real-context.ts ----
  { file: "packages/mcp/src/real-context.ts", snippet: "return {", reason: "Shared source line across 4 sites, all category-1: buildCapabilityClosureLookup's resolve() method start (returns { kind: \"block\", capabilities } -- static block-manifest capability metadata, covered by the standalone entry below), createRealEnginePort's object of closures wrapping engine.* calls (each closure's own return value flows through the engine's verified redaction before ever resolving), createRealGovernancePort's object of closures/pass-throughs to governance's real functions, and createRealRegistryPort's object of closures over the static block catalog. None of these object-literal starts is itself a data value -- each is a port/lookup object made of function references." },
  { file: "packages/mcp/src/real-context.ts", snippet: "return { kind: \"block\", capabilities: impl.manifest.capabilities };", reason: "impl.manifest.capabilities is a block's declared capability-string list (e.g. [\"browser\",\"http\"]) from the static block catalog -- capability vocabulary, not a resolved secret value." },
  { file: "packages/mcp/src/real-context.ts", snippet: "return async (workflow: Workflow, environment: string | undefined): Promise<string[]> => {", reason: "createGetGrantedCapabilities returns a CLOSURE (a function value) -- not data; nothing here is ever a persisted/emitted record. (The closure's own eventual return, a capability-string array, is covered by the getGrantedCapabilities(...) entry below.)" },
  { file: "packages/mcp/src/real-context.ts", snippet: "return getGrantedCapabilities({", reason: "Returns an array of capability-string vocabulary (e.g. \"browser\"/\"http\") computed from trustMode + workflow capability closure -- fixed vocabulary, not a resolved secret value." },
  { file: "packages/mcp/src/real-context.ts", snippet: "return async (_workflow: Workflow, _blocks: BlockRegistry): Promise<Record<string, string>> => {", reason: "createComputePackHashes returns a CLOSURE -- not data." },
  { file: "packages/mcp/src/real-context.ts", snippet: "return {};", reason: "Trivially empty object literal (documented gap: no pack-delivered blocks are in the registry yet, so this always resolves empty) -- nothing to redact." },
  { file: "packages/mcp/src/real-context.ts", snippet: "return createEngine({", reason: "Returns an ENGINE INSTANCE (an object of methods/closures from @aart/engine's createEngine) -- not a data-emission path; every one of its methods' own eventual return values is independently verified redacted (run-lifecycle.ts/step-executor.ts/wait-machine.ts)." },
  { file: "packages/mcp/src/real-context.ts", snippet: "return { id: newId(\"sig\"), name: input.name, correlationId: input.correlationId, payload: input.payload, receivedAt: new Date().toISOString() };", reason: "toRealSignal is an internal adapter building a Signal object to PASS INTO engine.resumeBySignal(...) -- not itself returned to a client; the engine's own verified redaction covers whatever this feeds into before it is ever persisted or returned." },
  { file: "packages/mcp/src/real-context.ts", snippet: "return finished.outputs ?? {};", reason: "finished is engine.executeRun()'s return value inside runEval's execute callback -- always the already-redacted RunRecord (verified end-to-end across run-lifecycle.ts/step-executor.ts/wait-machine.ts)." },
  { file: "packages/mcp/src/real-context.ts", snippet: "return result.evalRun;", reason: "result.evalRun is @aart/evidence's runEvalSuite output -- verified (evidence/src/evals/run-suite.ts) to be aggregate pass/fail/score/regressions[]/improvements[] summary data only, no raw example content." },
  { file: "packages/mcp/src/real-context.ts", snippet: "return filtered.map(({ score, ...entry }) => ({ entry, score }));", reason: "Block search results built from the static catalog (BlockCatalogEntry manifests) plus a numeric match score -- not run-resolved data, matching stubs/registry.ts's identical reasoning." },

  // ---- packages/mcp/src/recipes.ts ----
  { file: "packages/mcp/src/recipes.ts", snippet: "return new Set(text.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean));", reason: "wordSet tokenizes lowercased text for phrase matching -- an internal helper over the caller's own request string and the static hardcoded RECIPES phrase list, never returned to a client, never touches resolved secrets." },
  { file: "packages/mcp/src/recipes.ts", snippet: "return overlap > 0 ? (overlap / phraseTokens.length) * 40 : 0;", reason: "phraseScore returns a numeric match score -- not data." },
  { file: "packages/mcp/src/recipes.ts", snippet: "return results.sort((a, b) => b.score - a.score);", reason: "matchRecipes returns {recipe, score, matchedPhrase} entries where recipe is one of the static, hardcoded RECIPES entries (id/triggerPhrases/skeleton YAML) -- compile-time-authored content, never resolved secret data." },
  { file: "packages/mcp/src/recipes.ts", snippet: "return matchRecipes(request)[0]?.recipe;", reason: "Same static RECIPES content as above." },

  // ---- packages/mcp/src/response.ts ----
  { file: "packages/mcp/src/response.ts", snippet: "return NEXT_TABLE[tool][outcome];", reason: "computeNext looks up one of 42 hardcoded, static affordance strings from NEXT_TABLE -- no variable/run data." },
  { file: "packages/mcp/src/response.ts", snippet: "return { ...result, next: computeNext(tool, result.ok ? \"success\" : \"failure\") };", reason: "wrapResult only adds the static `next` affordance string on top of a handler's own already-vetted result -- each handler's own individual redaction reasoning (see its own file's suppression entries) covers `result` itself." },

  // ---- packages/mcp/src/stubs/engine.ts ----
  { file: "packages/mcp/src/stubs/engine.ts", snippet: "return `${prefix}_${Date.now().toString(36)}${counter.toString(36)}`;", reason: "newId builds a synthetic id string from a prefix + timestamp + counter -- no secret-shaped data." },
  { file: "packages/mcp/src/stubs/engine.ts", snippet: "return {", reason: "Shared source line, 6 sites in buildWaitCondition's switch (signal/timer/webhook/external_job/queue cases) -- each returns a WaitCondition built ONLY from step.with's own literal fields (typeof-guarded strings, e.g. w.name/w.correlationId/w.timeout) as authored directly in the workflow YAML/JSON; this stub never evaluates {{ }} expressions (no @aart/expr import anywhere in this file), so these fields can never contain a resolved secret value -- only whatever literal text the workflow author typed." },
  { file: "packages/mcp/src/stubs/engine.ts", snippet: "return { type: \"manual\", timeout: typeof w.timeout === \"string\" ? w.timeout : undefined, schemaVersion: 1 };", reason: "Same buildWaitCondition reasoning as above (wait.manual case) -- w.timeout is a literal field from step.with, never expression-resolved." },
  { file: "packages/mcp/src/stubs/engine.ts", snippet: "return { type: \"approval\", taskId: newId(\"task\"), timeout: typeof w.timeout === \"string\" ? w.timeout : undefined, schemaVersion: 1 };", reason: "Same buildWaitCondition reasoning (human.approval case) -- taskId is a synthesized id, timeout a literal field." },
  { file: "packages/mcp/src/stubs/engine.ts", snippet: "await store.waits.put(run.runId, step.id, wait, nowIso);", reason: "wait is the WaitCondition built by buildWaitCondition, covered by the entries above -- literal step.with fields only, never a resolved secret." },
  { file: "packages/mcp/src/stubs/engine.ts", snippet: "await store.runs.put(run);", reason: "Shared source line, 5 sites across advance()/triggerRun -- this stub engine has no @aart/expr/resolveSecret pipeline at all (verified: no import, no expression evaluation anywhere in this file); every \"block execute\" step statically produces outputs: {} (advance()'s per-step loop, line ~163), and run.inputs/trigger are copied verbatim from the MCP caller's own arguments (never template-resolved). There is no resolvedSecretRefs-shaped value this stub could ever construct, so redactRecord would always be a no-op even if wired in. (Production-reachable: createAartContext, wired by packages/cli/src/cli-context.ts into every real `aart` CLI/MCP invocation, uses this StubEngine, not createRealAartContext -- this is not merely a test fixture.)" },
  { file: "packages/mcp/src/stubs/engine.ts", snippet: "return run;", reason: "Shared source line, 4 sites -- returns the RunRecord this stub just mutated, covered by the store.runs.put(run) reasoning immediately above: no field on it can ever hold a resolved secret (no secrets pipeline exists in this file)." },
  { file: "packages/mcp/src/stubs/engine.ts", snippet: "return advance(run);", reason: "Delegates to advance(), covered by the store.runs.put(run)/return run reasoning above." },
  { file: "packages/mcp/src/stubs/engine.ts", snippet: "return { kind: \"resumed\", run: resumed };", reason: "resumed is advance()'s return value, covered by the same reasoning." },
  { file: "packages/mcp/src/stubs/engine.ts", snippet: "return this.resumeManual(match.runId, match.stepId, signal.payload);", reason: "Delegates to resumeManual, covered by the same reasoning -- signal.payload becomes trace outputs via a plain object-or-wrap assignment, never a resolved secret (no secrets pipeline in this file)." },
  { file: "packages/mcp/src/stubs/engine.ts", snippet: "return { kind: \"resumed\", run };", reason: "run is this function's own locally-mutated RunRecord, covered by the same reasoning as the other return-run sites in this file." },
  { file: "packages/mcp/src/stubs/engine.ts", snippet: "return this.resumeManual(runId, stepId, task.decision);", reason: "Delegates to resumeManual -- task.decision is human/agent-authored ApprovalTask decision content (same class as Correction.observed/corrected), not a resolved secret." },

  // ---- packages/mcp/src/stubs/evidence.ts ----
  { file: "packages/mcp/src/stubs/evidence.ts", snippet: "return \"Run completed successfully. Call aart_promote_workflow if this version is ready to promote, or aart_deploy_workflow if it's already approved.\";", reason: "Static hardcoded affordance string literal (nextForHeadline's \"passed\" case) -- no variable data." },
  { file: "packages/mcp/src/stubs/evidence.ts", snippet: "return \"Run failed — inspect failures[] for the failing step/block/error. Call aart_record_correction if the fix is a data/output correction, otherwise revise the workflow draft and call aart_validate again.\";", reason: "Static hardcoded affordance string literal (\"failed\" case) -- no variable data." },
  { file: "packages/mcp/src/stubs/evidence.ts", snippet: "return \"Run is waiting. Call aart_list_waiting_runs for details, then aart_resume_run (or aart_approve for a human.approval wait) to continue.\";", reason: "Static hardcoded affordance string literal (\"waiting\" case) -- no variable data." },
  { file: "packages/mcp/src/stubs/evidence.ts", snippet: "return {", reason: "buildModelFacingReport's return: { headline, workflowId, workflowVersion, failures, artifactRefs, next } -- failures/artifactRefs are derived from run.trace/run.artifacts, which per stubs/engine.ts's reasoning can never contain a resolved secret in this stub's world (no secrets pipeline exists anywhere in the stub layer)." },
  { file: "packages/mcp/src/stubs/evidence.ts", snippet: "return lines.join(\"\\n\");", reason: "buildMarkdownReport joins static-format lines built from run.runId/workflowId/workflowVersion/status/trace -- same \"never a resolved secret in this stub's world\" reasoning as buildModelFacingReport." },
  { file: "packages/mcp/src/stubs/evidence.ts", snippet: "return { passed: JSON.stringify(finished.outputs ?? {}) === JSON.stringify(example.expected) };", reason: "runOneExample's exact_match scorer -- a boolean comparison result; finished.outputs is this stub engine's statically-empty {} block output (stubs/engine.ts), example.expected is static EvalExample fixture data." },
  { file: "packages/mcp/src/stubs/evidence.ts", snippet: "return { passed: JSON.stringify(finished.outputs ?? {}).includes(example.expected) };", reason: "Same jsonpath_contains scorer reasoning as exact_match above -- a boolean result." },
  { file: "packages/mcp/src/stubs/evidence.ts", snippet: "return { passed: finished.status === \"completed\" };", reason: "Fallback scorer -- a boolean derived from run status, no content." },
  { file: "packages/mcp/src/stubs/evidence.ts", snippet: "await store.corrections.put(correction);", reason: "Same Correction reasoning as evidence/corrections/correction.ts: human/agent-authored free-form correction data supplied directly as this call's own input, no resolvedSecretRefs pipeline reaches this call site." },
  { file: "packages/mcp/src/stubs/evidence.ts", snippet: "return correction;", reason: "Returns the just-recorded Correction, covered by the entry immediately above." },
  { file: "packages/mcp/src/stubs/evidence.ts", snippet: "return example;", reason: "Returns the just-created EvalExample, built from Correction fields (observed/corrected) -- same correction-data class, not a resolved secret." },
  { file: "packages/mcp/src/stubs/evidence.ts", snippet: "return evalRun;", reason: "EvalRun aggregate summary data (id/suiteId/status/total/passed/failed/score/regressions[]/improvements[]) -- no raw example content, matching real-context.ts's runEvalSuite reasoning." },

  // ---- packages/mcp/src/stubs/governance.ts ----
  { file: "packages/mcp/src/stubs/governance.ts", snippet: "return MODES_WITH_AART_APPROVE.includes(mode);", reason: "isAartApproveRegisteredForMode returns a boolean membership check against a static 2-element TrustMode array -- no variable data." },
  { file: "packages/mcp/src/stubs/governance.ts", snippet: "return allSatisfied ? \"approved\" : \"draft\";", reason: "computeApprovalState returns one of 2 fixed AutoApprovalState string literals -- gate-state vocabulary, not run data." },
  { file: "packages/mcp/src/stubs/governance.ts", snippet: "return {", reason: "Shared source line, 4 sites: computePromotionState's PromotionRecord (environment/promoted/globalApproval/requiredGates/unmetGates -- all gate-name enum values and booleans), createStubGovernance's returned port object (methods/function references, not data), and 2 sites inside redact()'s own walk() helper (the array/object recursion branches -- this literally IS the redaction implementation, not a caller of it)." },
  { file: "packages/mcp/src/stubs/governance.ts", snippet: "return { blocked: true, reason: \"promotion_blocked\", environment: params.environment };", reason: "evaluatePromotionForEnvironment's blocked branch -- reason is a fixed string literal, environment is a caller-supplied identifier." },
  { file: "packages/mcp/src/stubs/governance.ts", snippet: "return { valid: false, findings };", reason: "validateWorkflow's schema-invalid branch -- findings are Zod schema-validation issues (class/path/message/severity) describing the DRAFT's own structural problems, echoing the caller's own input back for correction, never a resolved run secret." },
  { file: "packages/mcp/src/stubs/governance.ts", snippet: "return { valid: true, findings: [] };", reason: "Trivially empty findings array." },
  { file: "packages/mcp/src/stubs/governance.ts", snippet: "return JSON.stringify(a) === JSON.stringify(b);", reason: "deepEqual returns a boolean structural-equality result -- not data." },
  { file: "packages/mcp/src/stubs/governance.ts", snippet: "return details;", reason: "diffStepFields returns an array of STATIC change-description strings (e.g. \"step parameters changed\", \"condition changed from X to Y\" where X/Y are step.if/.then/.else/.next control-flow targets, not with: values) -- describes WHAT changed structurally, never echoes with: block content." },
  { file: "packages/mcp/src/stubs/governance.ts", snippet: "return result;", reason: "Inside redact()'s own walk() helper (string branch: result is the string AFTER redaction substitutions were applied) -- this is the redaction implementation itself, not a caller of it." },
  { file: "packages/mcp/src/stubs/governance.ts", snippet: "return out;", reason: "Inside redact()'s own walk() helper (object branch, building the redacted output object) -- same as above, the redaction implementation itself." },
  { file: "packages/mcp/src/stubs/governance.ts", snippet: "return node;", reason: "Inside redact()'s own walk() helper (fallthrough for null/number/boolean, which never carry a matchable string secret) -- the redaction implementation itself." },
  { file: "packages/mcp/src/stubs/governance.ts", snippet: "return { runId: `${WORKFLOW_VERSION_SUBJECT_PREFIX}${workflowId}@${workflowVersion}`, stepId: WORKFLOW_VERSION_SUBJECT_STEP_ID };", reason: "workflowVersionApprovalSubject builds a synthetic sentinel (runId/stepId) string pair from caller-supplied workflowId/workflowVersion identifiers and a fixed prefix/step-id constant -- not a resolved secret." },
  { file: "packages/mcp/src/stubs/governance.ts", snippet: "return { workflowId: rest.slice(0, at), workflowVersion: rest.slice(at + 1) };", reason: "decodeWorkflowVersionApprovalSubject parses the same synthetic sentinel string back into its two identifier parts -- not a resolved secret." },

  // ---- packages/mcp/src/stubs/registry.ts ----
  { file: "packages/mcp/src/stubs/registry.ts", snippet: "return new Set(text.toLowerCase().split(/[^a-z0-9.]+/).filter(Boolean));", reason: "wordSet tokenizes lowercased catalog/query text for matching -- an internal helper, never returned to a client, never touches resolved secrets." },
  { file: "packages/mcp/src/stubs/registry.ts", snippet: "return best;", reason: "score() returns a numeric match score -- not data." },
  { file: "packages/mcp/src/stubs/registry.ts", snippet: "return {", reason: "createStubRegistry's returned port object (findBlocks/listBlocks/getBlock methods) -- an object of function references, not data." },
  { file: "packages/mcp/src/stubs/registry.ts", snippet: "return catalog", reason: "findBlocks' return chain starts from the static, compile-time BUILTIN_BLOCK_CATALOG (catalog.ts) -- block manifests describing available tool/block types, never runtime secret data." },
  { file: "packages/mcp/src/stubs/registry.ts", snippet: "return catalog;", reason: "listBlocks returns the full static catalog -- same reasoning as findBlocks above." },
  { file: "packages/mcp/src/stubs/registry.ts", snippet: "return catalog.find((e) => e.manifest.id === id);", reason: "getBlock returns one static catalog entry -- same reasoning." },

  // ---- packages/mcp/src/test-utils.ts ----
  { file: "packages/mcp/src/test-utils.ts", snippet: "return fs.mkdtemp(join(tmpdir(), prefix));", reason: "Test-only helper (verified: imported exclusively by *.test.ts files across this package, zero non-test importers) -- creates a real OS temp directory path, no application data at all." },
  { file: "packages/mcp/src/test-utils.ts", snippet: "return { ctx, root, cleanup: () => cleanupTempRoot(root) };", reason: "Test-only helper (same verification as above) -- returns a test fixture bundle (an AartContext handle, a tmp path, a cleanup closure), not persisted/emitted application data." },
  { file: "packages/mcp/src/test-utils.ts", snippet: "return `id: ${id}", reason: "Test-only helper, 3 sites (sampleWorkflowYaml/approvalWaitWorkflowYaml/failingWorkflowYaml) -- each returns a hardcoded YAML fixture template string used only by this package's own tests; verified zero non-test importers of this file." },

  // ---- packages/mcp/src/tools/definitions.ts ----
  { file: "packages/mcp/src/tools/definitions.ts", snippet: "return def;", reason: "getToolDefinition returns one of the 21 statically-defined ToolDefinition entries (name/tier/description/inputSchema, all hardcoded Zod schemas and description strings) -- compile-time tool metadata, never run data." },

  // ---- packages/mcp/src/tools/server.ts ----
  { file: "packages/mcp/src/tools/server.ts", snippet: "return ctx.governance.isAartApproveRegisteredForMode(ctx.trustMode);", reason: "Delegates to a boolean-returning governance function over a TrustMode enum -- not data." },
  { file: "packages/mcp/src/tools/server.ts", snippet: "return environments.length > 0;", reason: "Returns a boolean (does at least one Environment record exist) -- not the records themselves." },
  { file: "packages/mcp/src/tools/server.ts", snippet: "return suites.length > 0;", reason: "Returns a boolean (does at least one EvalSuite exist) -- not the suites themselves." },
  { file: "packages/mcp/src/tools/server.ts", snippet: "return registered;", reason: "listRegisteredTools returns the filtered list of static ToolDefinition entries (tools/definitions.ts) -- compile-time tool metadata." },
  { file: "packages/mcp/src/tools/server.ts", snippet: "return (TOOL_NAMES as readonly string[]).includes(name);", reason: "isToolName returns a boolean membership check against the static 21-entry TOOL_NAMES array -- not data." },
  { file: "packages/mcp/src/tools/server.ts", snippet: "return {", reason: "createMcpServer's returned McpServerLike object (listTools/callTool methods) -- an object of function references, not data." },
  { file: "packages/mcp/src/tools/server.ts", snippet: "return { ok: false, error: `Unknown tool \"${name}\".`, next: \"Call listTools to see the currently available tools.\" };", reason: "name is the caller-supplied (invalid) tool-name string interpolated into a static error message -- not resolved run data." },
  { file: "packages/mcp/src/tools/server.ts", snippet: "return { ok: false, error: `Invalid arguments for \"${name}\": ${parsed.error.message}`, next: \"Fix the arguments and call this tool again.\" };", reason: "parsed.error.message is a Zod input-validation error describing what is structurally wrong with the CALLER'S OWN just-supplied arguments, echoed back for correction -- never a resolved run secret." },
  { file: "packages/mcp/src/tools/server.ts", snippet: "return wrapResult(name, result);", reason: "result is one of the 21 individual handlers' own return values -- each independently covered by that handler's own file's suppression entries above (authoring/deployment/discovery/evals/execution/governance handlers)." },

  // ---- packages/mcp/src/yaml-compiler.ts ----
  { file: "packages/mcp/src/yaml-compiler.ts", snippet: "return value !== null && typeof value === \"object\" && !Array.isArray(value);", reason: "isPlainObject returns a boolean type-check result -- not data." },
  { file: "packages/mcp/src/yaml-compiler.ts", snippet: "return Object.entries(source).map(([name, rawValue]) => {", reason: "compileFields builds the workflow's declared inputs:/outputs: Field[] SCHEMA (field names/types/defaults/enums/patterns, e.g. \"url: {type: string, required: true}\") -- author-declared schema metadata from the workflow DEFINITION, never a run-resolved value." },
  { file: "packages/mcp/src/yaml-compiler.ts", snippet: "return field as Field;", reason: "One compiled Field schema descriptor -- same reasoning as compileFields above." },
  { file: "packages/mcp/src/yaml-compiler.ts", snippet: "return out;", reason: "collectStrings recursively gathers every string value inside a step's with: block SOLELY to syntax-check {{ }} expression tokens (validateExpressions, via @aart/expr's parser) -- these are the workflow author's own literal, UNRESOLVED template strings (e.g. \"{{ secrets.X }}\" as typed, never evaluated), and this return value never itself reaches an MCP client; it is consumed only internally by validateExpressions." },
  { file: "packages/mcp/src/yaml-compiler.ts", snippet: "return parsed.data;", reason: "compileWorkflowObject returns the validated, compiled Workflow DEFINITION -- the pre-execution/authoring stage of the pipeline (template strings are validated for syntax only, never evaluated here); actual secrets.* resolution only happens later, inside @aart/engine's step dispatch, which is independently verified to redact before persist/return." },
  { file: "packages/mcp/src/yaml-compiler.ts", snippet: "return compileWorkflowObject(raw);", reason: "Delegates to compileWorkflowObject, covered by the entry immediately above." },

  // ---- packages/registry/src/import.ts ----
  { file: "packages/registry/src/import.ts", snippet: "await store.packManifests.put(manifest);", reason: "authorPack/installPack persist author-registered pack/block metadata (name, version, block source references, a hardcoded \"unapproved\" approvalStatus) built by buildPackManifest at authoring/install time -- registration-time configuration content, not a live run's resolved secret value." },

  // ---- packages/server/src/engine/boundary.ts ----
  { file: "packages/server/src/engine/boundary.ts", snippet: "await store.runs.put(run);", reason: "createFakeEngine.startRun -- a documented \"minimal, honest fake\" (module doc comment: \"NO step execution, NO wait/resume machine, NO capability dispatch\") with no @aart/expr/secrets-resolution pipeline of its own; run.inputs/trigger are copied verbatim from caller params, never resolved. Not reachable from the actually-shipping CLI: packages/cli/src/cli-context.ts wires createStubServerPort (a CLI-only, separate no-op stub), never this package's real worker/boundary machinery; any real deployment of @aart/server's worker uses createRealEngineBoundary instead, which is a thin pass-through to the real, independently-verified-redacted @aart/engine." },
  { file: "packages/server/src/engine/boundary.ts", snippet: "if (run) await tx.runs.put({ ...run, status: \"running\", updatedAt: clock.nowIso() });", reason: "createFakeEngine.resumeWithSignal/resumeDirect -- spreads an existing (already-safe, per the startRun reasoning above: this fake never resolves secrets) run with only static status/updatedAt fields added." },
  { file: "packages/server/src/engine/boundary.ts", snippet: "await store.runs.put({ ...run, status: \"completed\", updatedAt: clock.nowIso(), endedAt: clock.nowIso() });", reason: "createFakeEngine.executeClaimedRun -- same fake-engine reasoning as startRun above: spreads an existing run with only static status/timestamp fields, no step execution ever occurs in this fake." },

  // ---- packages/server/src/environments.ts ----
  { file: "packages/server/src/environments.ts", snippet: "await store.environments.put(environment);", reason: "registerEnvironment's Environment.secretSource is a SOURCE/config descriptor (where an environment's secrets are fetched from, e.g. a vault path or provider tag) supplied directly by an operator registering the environment -- a reference/config value, not a live run's resolved secret value, matching the established webhook-hmac-secret-ref reasoning (cli/src/commands/deployment.ts)." },
  { file: "packages/server/src/environments.ts", snippet: "await store.deployments.put(updated);", reason: "rollbackDeployment only changes workflowVersion (a caller-supplied version identifier) and createdAt on an existing Deployment -- deployment routing metadata, no run-resolved data." },

  // ---- packages/server/src/flags.ts ----
  { file: "packages/server/src/flags.ts", snippet: "await store.runs.put(updated);", reason: "clearRunFlag spreads an existing RunRecord with only a static { clearedBy, clearedAt } flag object added -- no new arbitrary content, matching the identical clearRunFlag implementations in cli/src/stubs/server.ts and dashboard/src/stub-deps.ts." },

  // ---- packages/server/src/http/server.ts ----
  { file: "packages/server/src/http/server.ts", snippet: "await config.store.approvals.put(updated);", reason: "The POST /approvals/:id/decision route's decision.decision is human/agent-authored free-form decision rationale supplied directly over HTTP by the caller -- same class as Correction.observed/corrected and dashboard's makeDecideApprovalTask, structurally outside resolvedSecretRefs' scope (no live-run secrets pipeline reaches an HTTP approval-decision route)." },

  // ---- packages/server/src/poison.ts ----
  { file: "packages/server/src/poison.ts", snippet: "* on that run via `store.runs.put()` when this returns true; this function", reason: "Not code at all -- this is a line from a /** */ JSDoc comment (shouldFlagPoison's doc, describing in PROSE that a CALLER is responsible for the actual store.runs.put() write). The lint's store-write pattern matches the literal text \"store.runs.put(\" wherever it appears on a line, including inside a block comment; there is no store write on this line." },

  // ---- packages/server/src/promotion.ts ----
  { file: "packages/server/src/promotion.ts", snippet: "await store.deployments.put(deployment);", reason: "promoteWorkflowVersionToEnvironment's Deployment.triggerConfig is caller-supplied trigger CONFIGURATION (params.triggerConfig, the same class of value as cli/src/commands/deployment.ts's trigger-config flags), not a resolved secret value." },

  // ---- packages/server/src/triggers/adapters.ts ----
  { file: "packages/server/src/triggers/adapters.ts", snippet: "await store.approvals.put(decided);", reason: "ingestGithubPrMergeApproval's decision field is a fixed-shape { source: \"github_pr_merge\", prNumber } provenance object built by this function itself -- not free-form/secret-shaped data." },

  // ---- packages/server/src/triggers/intake.ts ----
  { file: "packages/server/src/triggers/intake.ts", snippet: "await deps.store.rejectedTriggers.append(rejected);", reason: "rawPayload is the raw inbound delivery payload from an external trigger source (webhook/email/queue/etc.) -- third-party-supplied data this system never resolved via secrets.*, structurally outside the resolvedSecretRefs mechanism's scope, the same class as a workflow's own raw `inputs` (which this same lint's own architecture treats as out of scope throughout)." },

  // ---- packages/server/src/worker/reclaim.ts ----
  { file: "packages/server/src/worker/reclaim.ts", snippet: "await store.runs.put({", reason: "runReclaimSweep spreads an existing (already-safe, per @aart/engine's verified redaction invariant) run with only a static failed-status/error-fallback-message/flag object added -- no new arbitrary content." },

  // ---- packages/server/src/worker/worker.ts ----
  { file: "packages/server/src/worker/worker.ts", snippet: "await options.store.runs.put({ ...run, flag: { kind: \"poison\", flaggedAt: clock.nowIso() } });", reason: "maybeFlagPoison spreads an existing run with only a static { kind: \"poison\", flaggedAt } flag object added -- no new arbitrary content, matching the same flag-only-mutation pattern established across concurrency.ts/flags.ts/reclaim.ts." },
];
